spring:
  application:
    name: uaa-service
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  freemarker:
    enabled: true
    suffix: .html
    request-context-attribute: rc
    content-type: text/html
    charset: UTF-8
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false


  datasource:
    url: jdbc:mysql://121.196.163.158:3306/xiaoshanshan?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=CST
    username: root
    password: Shan19990524*
    driver-class-name: com.mysql.cj.jdbc.Driver


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8890/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}

server:
  port: 8888
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  use-forward-headers: true
  servlet:
    context-path: /uaa






logging:
  level:
    root: info
    org:
      springframework:
        web: info

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types[0]: text/html
      mime-types[1]: application/xml
      mime-types[2]: application/json
      min-request-size: 2048
    response:
      enabled: true


management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env