spring:
  application:
    name: distributed-discovery
server:
  port: 8890

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000
    shouldUseReadOnluyResponseCache: true
  client:
    register-with-eureka: false
    fetch-registry: false
    instance-info-replication-interval-seconds: 10
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
  instance:
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}
