server:
  port: 8080
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/xiaoshanshan?useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: Shan19990524*
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    port: 6379
    host: localhost
    database: 0
    password: 179980cs
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/*.xml

