spring:
  application:
    name: geteway-server
  main:
    allow-bean-definition-overriding: true
server:
  port: 8891

logging:
  level:
    root: info
    org:
      springframework: info

zuul:
  retryable: true
  add-host-header: true
  routes:
    uaa-service:
      stripPrefix: false
      path: /uaa/**

    order-service:
      stripPrefix: false
      path: /order/**
  ignoredServices: '*'
  sensitiveHeaders:
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000


ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 3000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8890/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}


management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env


feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types[0]: text/html
      mime-types[1]: application/xml
      mime-types[2]: application/json
      min-request-size: 2048
    response:
      enabled: true
